main:
  grammar_file: "data/grammar.pcfg"
  input: "../../data/train_sentences.txt"
  log_intervals: 10000
  log_path: "data/logs/"
  log_f:
    enabled: true
    intervals: 10000
  log_warning_in_training: false
  batch_size_for_parameter_update: -1
  split_data:
    enabled: true
    val_dataset_path: "../../data/validate_sentences.txt" 
    train_dataset_path: "../../data/train_sentences.txt"
    train_fraction: 0.8
  n_epochs: 5
  limit_n_sentences: -1

phase_convert:
  grammar_file: "data/grammar.pcfg"
  input: "data/eeg_sentences.txt"
  output: "data/sentences_converted.txt"

syntax_analysis:
  grammar_file: "../../data/grammar-trained.pcfg"
  input: "../../data/train_sentences.txt"
  log_intervals: 1000000
  log_path: "/data1/pcfg-logs/normal_train/"
  report_path: "/data1/pcfg-logs/reports/normal_train/"
  serialize_to_files: true
  tree_serialization_path: "/data1/pcfg-logs/serialized_tree/normal_train/"

test_parsing:
  grammar_file: "data/grammar-trained.pcfg"
  input: "data/pre-epileptic_integrated_all_d2_s4_converted.txt"
