# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sakuyui/Desktop/EEG-pcfg/pcfg-cky-inside-outside

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sakuyui/Desktop/EEG-pcfg/pcfg-cky-inside-outside

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sakuyui/Desktop/EEG-pcfg/pcfg-cky-inside-outside/CMakeFiles /home/sakuyui/Desktop/EEG-pcfg/pcfg-cky-inside-outside//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sakuyui/Desktop/EEG-pcfg/pcfg-cky-inside-outside/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shared_lib

# Build rule for target.
shared_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shared_lib
.PHONY : shared_lib

# fast build rule for target.
shared_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/build
.PHONY : shared_lib/fast

#=============================================================================
# Target rules for targets named distribution_lib

# Build rule for target.
distribution_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distribution_lib
.PHONY : distribution_lib

# fast build rule for target.
distribution_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distribution_lib.dir/build.make CMakeFiles/distribution_lib.dir/build
.PHONY : distribution_lib/fast

#=============================================================================
# Target rules for targets named train_pcfg

# Build rule for target.
train_pcfg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 train_pcfg
.PHONY : train_pcfg

# fast build rule for target.
train_pcfg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_pcfg.dir/build.make CMakeFiles/train_pcfg.dir/build
.PHONY : train_pcfg/fast

#=============================================================================
# Target rules for targets named phase_convert_executable

# Build rule for target.
phase_convert_executable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 phase_convert_executable
.PHONY : phase_convert_executable

# fast build rule for target.
phase_convert_executable/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase_convert_executable.dir/build.make CMakeFiles/phase_convert_executable.dir/build
.PHONY : phase_convert_executable/fast

#=============================================================================
# Target rules for targets named syntax_analysis

# Build rule for target.
syntax_analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 syntax_analysis
.PHONY : syntax_analysis

# fast build rule for target.
syntax_analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/syntax_analysis.dir/build.make CMakeFiles/syntax_analysis.dir/build
.PHONY : syntax_analysis/fast

#=============================================================================
# Target rules for targets named test_parsing

# Build rule for target.
test_parsing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_parsing
.PHONY : test_parsing

# fast build rule for target.
test_parsing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parsing.dir/build.make CMakeFiles/test_parsing.dir/build
.PHONY : test_parsing/fast

#=============================================================================
# Target rules for targets named distributed_training_main

# Build rule for target.
distributed_training_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distributed_training_main
.PHONY : distributed_training_main

# fast build rule for target.
distributed_training_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_training_main.dir/build.make CMakeFiles/distributed_training_main.dir/build
.PHONY : distributed_training_main/fast

#=============================================================================
# Target rules for targets named distributed_training_moderator

# Build rule for target.
distributed_training_moderator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distributed_training_moderator
.PHONY : distributed_training_moderator

# fast build rule for target.
distributed_training_moderator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_training_moderator.dir/build.make CMakeFiles/distributed_training_moderator.dir/build
.PHONY : distributed_training_moderator/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

src/algorithms/alg_inside_outside_main.o: src/algorithms/alg_inside_outside_main.cpp.o
.PHONY : src/algorithms/alg_inside_outside_main.o

# target to build an object file
src/algorithms/alg_inside_outside_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/algorithms/alg_inside_outside_main.cpp.o
.PHONY : src/algorithms/alg_inside_outside_main.cpp.o

src/algorithms/alg_inside_outside_main.i: src/algorithms/alg_inside_outside_main.cpp.i
.PHONY : src/algorithms/alg_inside_outside_main.i

# target to preprocess a source file
src/algorithms/alg_inside_outside_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/algorithms/alg_inside_outside_main.cpp.i
.PHONY : src/algorithms/alg_inside_outside_main.cpp.i

src/algorithms/alg_inside_outside_main.s: src/algorithms/alg_inside_outside_main.cpp.s
.PHONY : src/algorithms/alg_inside_outside_main.s

# target to generate assembly for a file
src/algorithms/alg_inside_outside_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/algorithms/alg_inside_outside_main.cpp.s
.PHONY : src/algorithms/alg_inside_outside_main.cpp.s

src/algorithms/tree_parser.o: src/algorithms/tree_parser.cpp.o
.PHONY : src/algorithms/tree_parser.o

# target to build an object file
src/algorithms/tree_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/algorithms/tree_parser.cpp.o
.PHONY : src/algorithms/tree_parser.cpp.o

src/algorithms/tree_parser.i: src/algorithms/tree_parser.cpp.i
.PHONY : src/algorithms/tree_parser.i

# target to preprocess a source file
src/algorithms/tree_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/algorithms/tree_parser.cpp.i
.PHONY : src/algorithms/tree_parser.cpp.i

src/algorithms/tree_parser.s: src/algorithms/tree_parser.cpp.s
.PHONY : src/algorithms/tree_parser.s

# target to generate assembly for a file
src/algorithms/tree_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/algorithms/tree_parser.cpp.s
.PHONY : src/algorithms/tree_parser.cpp.s

src/dataset/dataset_helper.o: src/dataset/dataset_helper.cpp.o
.PHONY : src/dataset/dataset_helper.o

# target to build an object file
src/dataset/dataset_helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/dataset/dataset_helper.cpp.o
.PHONY : src/dataset/dataset_helper.cpp.o

src/dataset/dataset_helper.i: src/dataset/dataset_helper.cpp.i
.PHONY : src/dataset/dataset_helper.i

# target to preprocess a source file
src/dataset/dataset_helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/dataset/dataset_helper.cpp.i
.PHONY : src/dataset/dataset_helper.cpp.i

src/dataset/dataset_helper.s: src/dataset/dataset_helper.cpp.s
.PHONY : src/dataset/dataset_helper.s

# target to generate assembly for a file
src/dataset/dataset_helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/dataset/dataset_helper.cpp.s
.PHONY : src/dataset/dataset_helper.cpp.s

src/debug/debug.o: src/debug/debug.cpp.o
.PHONY : src/debug/debug.o

# target to build an object file
src/debug/debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/debug/debug.cpp.o
.PHONY : src/debug/debug.cpp.o

src/debug/debug.i: src/debug/debug.cpp.i
.PHONY : src/debug/debug.i

# target to preprocess a source file
src/debug/debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/debug/debug.cpp.i
.PHONY : src/debug/debug.cpp.i

src/debug/debug.s: src/debug/debug.cpp.s
.PHONY : src/debug/debug.s

# target to generate assembly for a file
src/debug/debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/debug/debug.cpp.s
.PHONY : src/debug/debug.cpp.s

src/distributed_training_main.o: src/distributed_training_main.cpp.o
.PHONY : src/distributed_training_main.o

# target to build an object file
src/distributed_training_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/distributed_training_main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_training_main.dir/build.make CMakeFiles/distributed_training_main.dir/src/distributed_training_main.cpp.o
.PHONY : src/distributed_training_main.cpp.o

src/distributed_training_main.i: src/distributed_training_main.cpp.i
.PHONY : src/distributed_training_main.i

# target to preprocess a source file
src/distributed_training_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/distributed_training_main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_training_main.dir/build.make CMakeFiles/distributed_training_main.dir/src/distributed_training_main.cpp.i
.PHONY : src/distributed_training_main.cpp.i

src/distributed_training_main.s: src/distributed_training_main.cpp.s
.PHONY : src/distributed_training_main.s

# target to generate assembly for a file
src/distributed_training_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/distributed_training_main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_training_main.dir/build.make CMakeFiles/distributed_training_main.dir/src/distributed_training_main.cpp.s
.PHONY : src/distributed_training_main.cpp.s

src/distributed_training_moderator.o: src/distributed_training_moderator.cpp.o
.PHONY : src/distributed_training_moderator.o

# target to build an object file
src/distributed_training_moderator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/distributed_training_moderator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_training_moderator.dir/build.make CMakeFiles/distributed_training_moderator.dir/src/distributed_training_moderator.cpp.o
.PHONY : src/distributed_training_moderator.cpp.o

src/distributed_training_moderator.i: src/distributed_training_moderator.cpp.i
.PHONY : src/distributed_training_moderator.i

# target to preprocess a source file
src/distributed_training_moderator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/distributed_training_moderator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_training_moderator.dir/build.make CMakeFiles/distributed_training_moderator.dir/src/distributed_training_moderator.cpp.i
.PHONY : src/distributed_training_moderator.cpp.i

src/distributed_training_moderator.s: src/distributed_training_moderator.cpp.s
.PHONY : src/distributed_training_moderator.s

# target to generate assembly for a file
src/distributed_training_moderator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/distributed_training_moderator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_training_moderator.dir/build.make CMakeFiles/distributed_training_moderator.dir/src/distributed_training_moderator.cpp.s
.PHONY : src/distributed_training_moderator.cpp.s

src/distribution/package_manager.o: src/distribution/package_manager.cpp.o
.PHONY : src/distribution/package_manager.o

# target to build an object file
src/distribution/package_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distribution_lib.dir/build.make CMakeFiles/distribution_lib.dir/src/distribution/package_manager.cpp.o
.PHONY : src/distribution/package_manager.cpp.o

src/distribution/package_manager.i: src/distribution/package_manager.cpp.i
.PHONY : src/distribution/package_manager.i

# target to preprocess a source file
src/distribution/package_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distribution_lib.dir/build.make CMakeFiles/distribution_lib.dir/src/distribution/package_manager.cpp.i
.PHONY : src/distribution/package_manager.cpp.i

src/distribution/package_manager.s: src/distribution/package_manager.cpp.s
.PHONY : src/distribution/package_manager.s

# target to generate assembly for a file
src/distribution/package_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distribution_lib.dir/build.make CMakeFiles/distribution_lib.dir/src/distribution/package_manager.cpp.s
.PHONY : src/distribution/package_manager.cpp.s

src/distribution/services.o: src/distribution/services.cpp.o
.PHONY : src/distribution/services.o

# target to build an object file
src/distribution/services.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distribution_lib.dir/build.make CMakeFiles/distribution_lib.dir/src/distribution/services.cpp.o
.PHONY : src/distribution/services.cpp.o

src/distribution/services.i: src/distribution/services.cpp.i
.PHONY : src/distribution/services.i

# target to preprocess a source file
src/distribution/services.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distribution_lib.dir/build.make CMakeFiles/distribution_lib.dir/src/distribution/services.cpp.i
.PHONY : src/distribution/services.cpp.i

src/distribution/services.s: src/distribution/services.cpp.s
.PHONY : src/distribution/services.s

# target to generate assembly for a file
src/distribution/services.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distribution_lib.dir/build.make CMakeFiles/distribution_lib.dir/src/distribution/services.cpp.s
.PHONY : src/distribution/services.cpp.s

src/distribution/shared_memory.o: src/distribution/shared_memory.cpp.o
.PHONY : src/distribution/shared_memory.o

# target to build an object file
src/distribution/shared_memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distribution_lib.dir/build.make CMakeFiles/distribution_lib.dir/src/distribution/shared_memory.cpp.o
.PHONY : src/distribution/shared_memory.cpp.o

src/distribution/shared_memory.i: src/distribution/shared_memory.cpp.i
.PHONY : src/distribution/shared_memory.i

# target to preprocess a source file
src/distribution/shared_memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distribution_lib.dir/build.make CMakeFiles/distribution_lib.dir/src/distribution/shared_memory.cpp.i
.PHONY : src/distribution/shared_memory.cpp.i

src/distribution/shared_memory.s: src/distribution/shared_memory.cpp.s
.PHONY : src/distribution/shared_memory.s

# target to generate assembly for a file
src/distribution/shared_memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distribution_lib.dir/build.make CMakeFiles/distribution_lib.dir/src/distribution/shared_memory.cpp.s
.PHONY : src/distribution/shared_memory.cpp.s

src/grammar/grammar.o: src/grammar/grammar.cpp.o
.PHONY : src/grammar/grammar.o

# target to build an object file
src/grammar/grammar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/grammar/grammar.cpp.o
.PHONY : src/grammar/grammar.cpp.o

src/grammar/grammar.i: src/grammar/grammar.cpp.i
.PHONY : src/grammar/grammar.i

# target to preprocess a source file
src/grammar/grammar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/grammar/grammar.cpp.i
.PHONY : src/grammar/grammar.cpp.i

src/grammar/grammar.s: src/grammar/grammar.cpp.s
.PHONY : src/grammar/grammar.s

# target to generate assembly for a file
src/grammar/grammar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/grammar/grammar.cpp.s
.PHONY : src/grammar/grammar.cpp.s

src/grammar/grammar_normalizer.o: src/grammar/grammar_normalizer.cpp.o
.PHONY : src/grammar/grammar_normalizer.o

# target to build an object file
src/grammar/grammar_normalizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/grammar/grammar_normalizer.cpp.o
.PHONY : src/grammar/grammar_normalizer.cpp.o

src/grammar/grammar_normalizer.i: src/grammar/grammar_normalizer.cpp.i
.PHONY : src/grammar/grammar_normalizer.i

# target to preprocess a source file
src/grammar/grammar_normalizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/grammar/grammar_normalizer.cpp.i
.PHONY : src/grammar/grammar_normalizer.cpp.i

src/grammar/grammar_normalizer.s: src/grammar/grammar_normalizer.cpp.s
.PHONY : src/grammar/grammar_normalizer.s

# target to generate assembly for a file
src/grammar/grammar_normalizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/grammar/grammar_normalizer.cpp.s
.PHONY : src/grammar/grammar_normalizer.cpp.s

src/grammar/grammar_parser.o: src/grammar/grammar_parser.cpp.o
.PHONY : src/grammar/grammar_parser.o

# target to build an object file
src/grammar/grammar_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/grammar/grammar_parser.cpp.o
.PHONY : src/grammar/grammar_parser.cpp.o

src/grammar/grammar_parser.i: src/grammar/grammar_parser.cpp.i
.PHONY : src/grammar/grammar_parser.i

# target to preprocess a source file
src/grammar/grammar_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/grammar/grammar_parser.cpp.i
.PHONY : src/grammar/grammar_parser.cpp.i

src/grammar/grammar_parser.s: src/grammar/grammar_parser.cpp.s
.PHONY : src/grammar/grammar_parser.s

# target to generate assembly for a file
src/grammar/grammar_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/grammar/grammar_parser.cpp.s
.PHONY : src/grammar/grammar_parser.cpp.s

src/kernels/expect_count.o: src/kernels/expect_count.cpp.o
.PHONY : src/kernels/expect_count.o

# target to build an object file
src/kernels/expect_count.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/kernels/expect_count.cpp.o
.PHONY : src/kernels/expect_count.cpp.o

src/kernels/expect_count.i: src/kernels/expect_count.cpp.i
.PHONY : src/kernels/expect_count.i

# target to preprocess a source file
src/kernels/expect_count.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/kernels/expect_count.cpp.i
.PHONY : src/kernels/expect_count.cpp.i

src/kernels/expect_count.s: src/kernels/expect_count.cpp.s
.PHONY : src/kernels/expect_count.s

# target to generate assembly for a file
src/kernels/expect_count.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/kernels/expect_count.cpp.s
.PHONY : src/kernels/expect_count.cpp.s

src/kernels/inside.o: src/kernels/inside.cpp.o
.PHONY : src/kernels/inside.o

# target to build an object file
src/kernels/inside.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/kernels/inside.cpp.o
.PHONY : src/kernels/inside.cpp.o

src/kernels/inside.i: src/kernels/inside.cpp.i
.PHONY : src/kernels/inside.i

# target to preprocess a source file
src/kernels/inside.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/kernels/inside.cpp.i
.PHONY : src/kernels/inside.cpp.i

src/kernels/inside.s: src/kernels/inside.cpp.s
.PHONY : src/kernels/inside.s

# target to generate assembly for a file
src/kernels/inside.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/kernels/inside.cpp.s
.PHONY : src/kernels/inside.cpp.s

src/kernels/outside.o: src/kernels/outside.cpp.o
.PHONY : src/kernels/outside.o

# target to build an object file
src/kernels/outside.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/kernels/outside.cpp.o
.PHONY : src/kernels/outside.cpp.o

src/kernels/outside.i: src/kernels/outside.cpp.i
.PHONY : src/kernels/outside.i

# target to preprocess a source file
src/kernels/outside.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/kernels/outside.cpp.i
.PHONY : src/kernels/outside.cpp.i

src/kernels/outside.s: src/kernels/outside.cpp.s
.PHONY : src/kernels/outside.s

# target to generate assembly for a file
src/kernels/outside.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/kernels/outside.cpp.s
.PHONY : src/kernels/outside.cpp.s

src/kernels/update_parameters.o: src/kernels/update_parameters.cpp.o
.PHONY : src/kernels/update_parameters.o

# target to build an object file
src/kernels/update_parameters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/kernels/update_parameters.cpp.o
.PHONY : src/kernels/update_parameters.cpp.o

src/kernels/update_parameters.i: src/kernels/update_parameters.cpp.i
.PHONY : src/kernels/update_parameters.i

# target to preprocess a source file
src/kernels/update_parameters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/kernels/update_parameters.cpp.i
.PHONY : src/kernels/update_parameters.cpp.i

src/kernels/update_parameters.s: src/kernels/update_parameters.cpp.s
.PHONY : src/kernels/update_parameters.s

# target to generate assembly for a file
src/kernels/update_parameters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/kernels/update_parameters.cpp.s
.PHONY : src/kernels/update_parameters.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_pcfg.dir/build.make CMakeFiles/train_pcfg.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_pcfg.dir/build.make CMakeFiles/train_pcfg.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train_pcfg.dir/build.make CMakeFiles/train_pcfg.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/phase_convert.o: src/phase_convert.cpp.o
.PHONY : src/phase_convert.o

# target to build an object file
src/phase_convert.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/phase_convert.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase_convert_executable.dir/build.make CMakeFiles/phase_convert_executable.dir/src/phase_convert.cpp.o
.PHONY : src/phase_convert.cpp.o

src/phase_convert.i: src/phase_convert.cpp.i
.PHONY : src/phase_convert.i

# target to preprocess a source file
src/phase_convert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/phase_convert.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase_convert_executable.dir/build.make CMakeFiles/phase_convert_executable.dir/src/phase_convert.cpp.i
.PHONY : src/phase_convert.cpp.i

src/phase_convert.s: src/phase_convert.cpp.s
.PHONY : src/phase_convert.s

# target to generate assembly for a file
src/phase_convert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/phase_convert.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase_convert_executable.dir/build.make CMakeFiles/phase_convert_executable.dir/src/phase_convert.cpp.s
.PHONY : src/phase_convert.cpp.s

src/statistics/entropy_utils.o: src/statistics/entropy_utils.cpp.o
.PHONY : src/statistics/entropy_utils.o

# target to build an object file
src/statistics/entropy_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/entropy_utils.cpp.o
.PHONY : src/statistics/entropy_utils.cpp.o

src/statistics/entropy_utils.i: src/statistics/entropy_utils.cpp.i
.PHONY : src/statistics/entropy_utils.i

# target to preprocess a source file
src/statistics/entropy_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/entropy_utils.cpp.i
.PHONY : src/statistics/entropy_utils.cpp.i

src/statistics/entropy_utils.s: src/statistics/entropy_utils.cpp.s
.PHONY : src/statistics/entropy_utils.s

# target to generate assembly for a file
src/statistics/entropy_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/entropy_utils.cpp.s
.PHONY : src/statistics/entropy_utils.cpp.s

src/statistics/statistics_main.o: src/statistics/statistics_main.cpp.o
.PHONY : src/statistics/statistics_main.o

# target to build an object file
src/statistics/statistics_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/statistics_main.cpp.o
.PHONY : src/statistics/statistics_main.cpp.o

src/statistics/statistics_main.i: src/statistics/statistics_main.cpp.i
.PHONY : src/statistics/statistics_main.i

# target to preprocess a source file
src/statistics/statistics_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/statistics_main.cpp.i
.PHONY : src/statistics/statistics_main.cpp.i

src/statistics/statistics_main.s: src/statistics/statistics_main.cpp.s
.PHONY : src/statistics/statistics_main.s

# target to generate assembly for a file
src/statistics/statistics_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/statistics_main.cpp.s
.PHONY : src/statistics/statistics_main.cpp.s

src/statistics/tree_feature_statistics.o: src/statistics/tree_feature_statistics.cpp.o
.PHONY : src/statistics/tree_feature_statistics.o

# target to build an object file
src/statistics/tree_feature_statistics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/tree_feature_statistics.cpp.o
.PHONY : src/statistics/tree_feature_statistics.cpp.o

src/statistics/tree_feature_statistics.i: src/statistics/tree_feature_statistics.cpp.i
.PHONY : src/statistics/tree_feature_statistics.i

# target to preprocess a source file
src/statistics/tree_feature_statistics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/tree_feature_statistics.cpp.i
.PHONY : src/statistics/tree_feature_statistics.cpp.i

src/statistics/tree_feature_statistics.s: src/statistics/tree_feature_statistics.cpp.s
.PHONY : src/statistics/tree_feature_statistics.s

# target to generate assembly for a file
src/statistics/tree_feature_statistics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/tree_feature_statistics.cpp.s
.PHONY : src/statistics/tree_feature_statistics.cpp.s

src/statistics/tree_informatics_feature_statistics.o: src/statistics/tree_informatics_feature_statistics.cpp.o
.PHONY : src/statistics/tree_informatics_feature_statistics.o

# target to build an object file
src/statistics/tree_informatics_feature_statistics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/tree_informatics_feature_statistics.cpp.o
.PHONY : src/statistics/tree_informatics_feature_statistics.cpp.o

src/statistics/tree_informatics_feature_statistics.i: src/statistics/tree_informatics_feature_statistics.cpp.i
.PHONY : src/statistics/tree_informatics_feature_statistics.i

# target to preprocess a source file
src/statistics/tree_informatics_feature_statistics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/tree_informatics_feature_statistics.cpp.i
.PHONY : src/statistics/tree_informatics_feature_statistics.cpp.i

src/statistics/tree_informatics_feature_statistics.s: src/statistics/tree_informatics_feature_statistics.cpp.s
.PHONY : src/statistics/tree_informatics_feature_statistics.s

# target to generate assembly for a file
src/statistics/tree_informatics_feature_statistics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/tree_informatics_feature_statistics.cpp.s
.PHONY : src/statistics/tree_informatics_feature_statistics.cpp.s

src/statistics/tree_utils.o: src/statistics/tree_utils.cpp.o
.PHONY : src/statistics/tree_utils.o

# target to build an object file
src/statistics/tree_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/tree_utils.cpp.o
.PHONY : src/statistics/tree_utils.cpp.o

src/statistics/tree_utils.i: src/statistics/tree_utils.cpp.i
.PHONY : src/statistics/tree_utils.i

# target to preprocess a source file
src/statistics/tree_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/tree_utils.cpp.i
.PHONY : src/statistics/tree_utils.cpp.i

src/statistics/tree_utils.s: src/statistics/tree_utils.cpp.s
.PHONY : src/statistics/tree_utils.s

# target to generate assembly for a file
src/statistics/tree_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/statistics/tree_utils.cpp.s
.PHONY : src/statistics/tree_utils.cpp.s

src/syntax_analysis.o: src/syntax_analysis.cpp.o
.PHONY : src/syntax_analysis.o

# target to build an object file
src/syntax_analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/syntax_analysis.dir/build.make CMakeFiles/syntax_analysis.dir/src/syntax_analysis.cpp.o
.PHONY : src/syntax_analysis.cpp.o

src/syntax_analysis.i: src/syntax_analysis.cpp.i
.PHONY : src/syntax_analysis.i

# target to preprocess a source file
src/syntax_analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/syntax_analysis.dir/build.make CMakeFiles/syntax_analysis.dir/src/syntax_analysis.cpp.i
.PHONY : src/syntax_analysis.cpp.i

src/syntax_analysis.s: src/syntax_analysis.cpp.s
.PHONY : src/syntax_analysis.s

# target to generate assembly for a file
src/syntax_analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/syntax_analysis.dir/build.make CMakeFiles/syntax_analysis.dir/src/syntax_analysis.cpp.s
.PHONY : src/syntax_analysis.cpp.s

src/test/test_parsing.o: src/test/test_parsing.cpp.o
.PHONY : src/test/test_parsing.o

# target to build an object file
src/test/test_parsing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/test/test_parsing.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parsing.dir/build.make CMakeFiles/test_parsing.dir/src/test/test_parsing.cpp.o
.PHONY : src/test/test_parsing.cpp.o

src/test/test_parsing.i: src/test/test_parsing.cpp.i
.PHONY : src/test/test_parsing.i

# target to preprocess a source file
src/test/test_parsing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/test/test_parsing.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parsing.dir/build.make CMakeFiles/test_parsing.dir/src/test/test_parsing.cpp.i
.PHONY : src/test/test_parsing.cpp.i

src/test/test_parsing.s: src/test/test_parsing.cpp.s
.PHONY : src/test/test_parsing.s

# target to generate assembly for a file
src/test/test_parsing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/test/test_parsing.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parsing.dir/build.make CMakeFiles/test_parsing.dir/src/test/test_parsing.cpp.s
.PHONY : src/test/test_parsing.cpp.s

src/utils/application_io.o: src/utils/application_io.cpp.o
.PHONY : src/utils/application_io.o

# target to build an object file
src/utils/application_io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/application_io.cpp.o
.PHONY : src/utils/application_io.cpp.o

src/utils/application_io.i: src/utils/application_io.cpp.i
.PHONY : src/utils/application_io.i

# target to preprocess a source file
src/utils/application_io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/application_io.cpp.i
.PHONY : src/utils/application_io.cpp.i

src/utils/application_io.s: src/utils/application_io.cpp.s
.PHONY : src/utils/application_io.s

# target to generate assembly for a file
src/utils/application_io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/application_io.cpp.s
.PHONY : src/utils/application_io.cpp.s

src/utils/data_accessing.o: src/utils/data_accessing.cpp.o
.PHONY : src/utils/data_accessing.o

# target to build an object file
src/utils/data_accessing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/data_accessing.cpp.o
.PHONY : src/utils/data_accessing.cpp.o

src/utils/data_accessing.i: src/utils/data_accessing.cpp.i
.PHONY : src/utils/data_accessing.i

# target to preprocess a source file
src/utils/data_accessing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/data_accessing.cpp.i
.PHONY : src/utils/data_accessing.cpp.i

src/utils/data_accessing.s: src/utils/data_accessing.cpp.s
.PHONY : src/utils/data_accessing.s

# target to generate assembly for a file
src/utils/data_accessing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/data_accessing.cpp.s
.PHONY : src/utils/data_accessing.cpp.s

src/utils/data_encoding.o: src/utils/data_encoding.cpp.o
.PHONY : src/utils/data_encoding.o

# target to build an object file
src/utils/data_encoding.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/data_encoding.cpp.o
.PHONY : src/utils/data_encoding.cpp.o

src/utils/data_encoding.i: src/utils/data_encoding.cpp.i
.PHONY : src/utils/data_encoding.i

# target to preprocess a source file
src/utils/data_encoding.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/data_encoding.cpp.i
.PHONY : src/utils/data_encoding.cpp.i

src/utils/data_encoding.s: src/utils/data_encoding.cpp.s
.PHONY : src/utils/data_encoding.s

# target to generate assembly for a file
src/utils/data_encoding.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/data_encoding.cpp.s
.PHONY : src/utils/data_encoding.cpp.s

src/utils/data_structure.o: src/utils/data_structure.cpp.o
.PHONY : src/utils/data_structure.o

# target to build an object file
src/utils/data_structure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/data_structure.cpp.o
.PHONY : src/utils/data_structure.cpp.o

src/utils/data_structure.i: src/utils/data_structure.cpp.i
.PHONY : src/utils/data_structure.i

# target to preprocess a source file
src/utils/data_structure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/data_structure.cpp.i
.PHONY : src/utils/data_structure.cpp.i

src/utils/data_structure.s: src/utils/data_structure.cpp.s
.PHONY : src/utils/data_structure.s

# target to generate assembly for a file
src/utils/data_structure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/data_structure.cpp.s
.PHONY : src/utils/data_structure.cpp.s

src/utils/logger.o: src/utils/logger.cpp.o
.PHONY : src/utils/logger.o

# target to build an object file
src/utils/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/logger.cpp.o
.PHONY : src/utils/logger.cpp.o

src/utils/logger.i: src/utils/logger.cpp.i
.PHONY : src/utils/logger.i

# target to preprocess a source file
src/utils/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/logger.cpp.i
.PHONY : src/utils/logger.cpp.i

src/utils/logger.s: src/utils/logger.cpp.s
.PHONY : src/utils/logger.s

# target to generate assembly for a file
src/utils/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/logger.cpp.s
.PHONY : src/utils/logger.cpp.s

src/utils/math.o: src/utils/math.cpp.o
.PHONY : src/utils/math.o

# target to build an object file
src/utils/math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/math.cpp.o
.PHONY : src/utils/math.cpp.o

src/utils/math.i: src/utils/math.cpp.i
.PHONY : src/utils/math.i

# target to preprocess a source file
src/utils/math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/math.cpp.i
.PHONY : src/utils/math.cpp.i

src/utils/math.s: src/utils/math.cpp.s
.PHONY : src/utils/math.s

# target to generate assembly for a file
src/utils/math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/math.cpp.s
.PHONY : src/utils/math.cpp.s

src/utils/printer.o: src/utils/printer.cpp.o
.PHONY : src/utils/printer.o

# target to build an object file
src/utils/printer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/printer.cpp.o
.PHONY : src/utils/printer.cpp.o

src/utils/printer.i: src/utils/printer.cpp.i
.PHONY : src/utils/printer.i

# target to preprocess a source file
src/utils/printer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/printer.cpp.i
.PHONY : src/utils/printer.cpp.i

src/utils/printer.s: src/utils/printer.cpp.s
.PHONY : src/utils/printer.s

# target to generate assembly for a file
src/utils/printer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/printer.cpp.s
.PHONY : src/utils/printer.cpp.s

src/utils/string_helper.o: src/utils/string_helper.cpp.o
.PHONY : src/utils/string_helper.o

# target to build an object file
src/utils/string_helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/string_helper.cpp.o
.PHONY : src/utils/string_helper.cpp.o

src/utils/string_helper.i: src/utils/string_helper.cpp.i
.PHONY : src/utils/string_helper.i

# target to preprocess a source file
src/utils/string_helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/string_helper.cpp.i
.PHONY : src/utils/string_helper.cpp.i

src/utils/string_helper.s: src/utils/string_helper.cpp.s
.PHONY : src/utils/string_helper.s

# target to generate assembly for a file
src/utils/string_helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/string_helper.cpp.s
.PHONY : src/utils/string_helper.cpp.s

src/utils/tensor.o: src/utils/tensor.cpp.o
.PHONY : src/utils/tensor.o

# target to build an object file
src/utils/tensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/tensor.cpp.o
.PHONY : src/utils/tensor.cpp.o

src/utils/tensor.i: src/utils/tensor.cpp.i
.PHONY : src/utils/tensor.i

# target to preprocess a source file
src/utils/tensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/tensor.cpp.i
.PHONY : src/utils/tensor.cpp.i

src/utils/tensor.s: src/utils/tensor.cpp.s
.PHONY : src/utils/tensor.s

# target to generate assembly for a file
src/utils/tensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_lib.dir/build.make CMakeFiles/shared_lib.dir/src/utils/tensor.cpp.s
.PHONY : src/utils/tensor.cpp.s

unit_test/hashtable_test.o: unit_test/hashtable_test.cpp.o
.PHONY : unit_test/hashtable_test.o

# target to build an object file
unit_test/hashtable_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unit_test/hashtable_test.cpp.o
.PHONY : unit_test/hashtable_test.cpp.o

unit_test/hashtable_test.i: unit_test/hashtable_test.cpp.i
.PHONY : unit_test/hashtable_test.i

# target to preprocess a source file
unit_test/hashtable_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unit_test/hashtable_test.cpp.i
.PHONY : unit_test/hashtable_test.cpp.i

unit_test/hashtable_test.s: unit_test/hashtable_test.cpp.s
.PHONY : unit_test/hashtable_test.s

# target to generate assembly for a file
unit_test/hashtable_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unit_test/hashtable_test.cpp.s
.PHONY : unit_test/hashtable_test.cpp.s

unit_test/inside_test.o: unit_test/inside_test.cpp.o
.PHONY : unit_test/inside_test.o

# target to build an object file
unit_test/inside_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unit_test/inside_test.cpp.o
.PHONY : unit_test/inside_test.cpp.o

unit_test/inside_test.i: unit_test/inside_test.cpp.i
.PHONY : unit_test/inside_test.i

# target to preprocess a source file
unit_test/inside_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unit_test/inside_test.cpp.i
.PHONY : unit_test/inside_test.cpp.i

unit_test/inside_test.s: unit_test/inside_test.cpp.s
.PHONY : unit_test/inside_test.s

# target to generate assembly for a file
unit_test/inside_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unit_test/inside_test.cpp.s
.PHONY : unit_test/inside_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run_tests"
	@echo "... distributed_training_main"
	@echo "... distributed_training_moderator"
	@echo "... distribution_lib"
	@echo "... phase_convert_executable"
	@echo "... shared_lib"
	@echo "... syntax_analysis"
	@echo "... test_parsing"
	@echo "... train_pcfg"
	@echo "... unit_tests"
	@echo "... src/algorithms/alg_inside_outside_main.o"
	@echo "... src/algorithms/alg_inside_outside_main.i"
	@echo "... src/algorithms/alg_inside_outside_main.s"
	@echo "... src/algorithms/tree_parser.o"
	@echo "... src/algorithms/tree_parser.i"
	@echo "... src/algorithms/tree_parser.s"
	@echo "... src/dataset/dataset_helper.o"
	@echo "... src/dataset/dataset_helper.i"
	@echo "... src/dataset/dataset_helper.s"
	@echo "... src/debug/debug.o"
	@echo "... src/debug/debug.i"
	@echo "... src/debug/debug.s"
	@echo "... src/distributed_training_main.o"
	@echo "... src/distributed_training_main.i"
	@echo "... src/distributed_training_main.s"
	@echo "... src/distributed_training_moderator.o"
	@echo "... src/distributed_training_moderator.i"
	@echo "... src/distributed_training_moderator.s"
	@echo "... src/distribution/package_manager.o"
	@echo "... src/distribution/package_manager.i"
	@echo "... src/distribution/package_manager.s"
	@echo "... src/distribution/services.o"
	@echo "... src/distribution/services.i"
	@echo "... src/distribution/services.s"
	@echo "... src/distribution/shared_memory.o"
	@echo "... src/distribution/shared_memory.i"
	@echo "... src/distribution/shared_memory.s"
	@echo "... src/grammar/grammar.o"
	@echo "... src/grammar/grammar.i"
	@echo "... src/grammar/grammar.s"
	@echo "... src/grammar/grammar_normalizer.o"
	@echo "... src/grammar/grammar_normalizer.i"
	@echo "... src/grammar/grammar_normalizer.s"
	@echo "... src/grammar/grammar_parser.o"
	@echo "... src/grammar/grammar_parser.i"
	@echo "... src/grammar/grammar_parser.s"
	@echo "... src/kernels/expect_count.o"
	@echo "... src/kernels/expect_count.i"
	@echo "... src/kernels/expect_count.s"
	@echo "... src/kernels/inside.o"
	@echo "... src/kernels/inside.i"
	@echo "... src/kernels/inside.s"
	@echo "... src/kernels/outside.o"
	@echo "... src/kernels/outside.i"
	@echo "... src/kernels/outside.s"
	@echo "... src/kernels/update_parameters.o"
	@echo "... src/kernels/update_parameters.i"
	@echo "... src/kernels/update_parameters.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/phase_convert.o"
	@echo "... src/phase_convert.i"
	@echo "... src/phase_convert.s"
	@echo "... src/statistics/entropy_utils.o"
	@echo "... src/statistics/entropy_utils.i"
	@echo "... src/statistics/entropy_utils.s"
	@echo "... src/statistics/statistics_main.o"
	@echo "... src/statistics/statistics_main.i"
	@echo "... src/statistics/statistics_main.s"
	@echo "... src/statistics/tree_feature_statistics.o"
	@echo "... src/statistics/tree_feature_statistics.i"
	@echo "... src/statistics/tree_feature_statistics.s"
	@echo "... src/statistics/tree_informatics_feature_statistics.o"
	@echo "... src/statistics/tree_informatics_feature_statistics.i"
	@echo "... src/statistics/tree_informatics_feature_statistics.s"
	@echo "... src/statistics/tree_utils.o"
	@echo "... src/statistics/tree_utils.i"
	@echo "... src/statistics/tree_utils.s"
	@echo "... src/syntax_analysis.o"
	@echo "... src/syntax_analysis.i"
	@echo "... src/syntax_analysis.s"
	@echo "... src/test/test_parsing.o"
	@echo "... src/test/test_parsing.i"
	@echo "... src/test/test_parsing.s"
	@echo "... src/utils/application_io.o"
	@echo "... src/utils/application_io.i"
	@echo "... src/utils/application_io.s"
	@echo "... src/utils/data_accessing.o"
	@echo "... src/utils/data_accessing.i"
	@echo "... src/utils/data_accessing.s"
	@echo "... src/utils/data_encoding.o"
	@echo "... src/utils/data_encoding.i"
	@echo "... src/utils/data_encoding.s"
	@echo "... src/utils/data_structure.o"
	@echo "... src/utils/data_structure.i"
	@echo "... src/utils/data_structure.s"
	@echo "... src/utils/logger.o"
	@echo "... src/utils/logger.i"
	@echo "... src/utils/logger.s"
	@echo "... src/utils/math.o"
	@echo "... src/utils/math.i"
	@echo "... src/utils/math.s"
	@echo "... src/utils/printer.o"
	@echo "... src/utils/printer.i"
	@echo "... src/utils/printer.s"
	@echo "... src/utils/string_helper.o"
	@echo "... src/utils/string_helper.i"
	@echo "... src/utils/string_helper.s"
	@echo "... src/utils/tensor.o"
	@echo "... src/utils/tensor.i"
	@echo "... src/utils/tensor.s"
	@echo "... unit_test/hashtable_test.o"
	@echo "... unit_test/hashtable_test.i"
	@echo "... unit_test/hashtable_test.s"
	@echo "... unit_test/inside_test.o"
	@echo "... unit_test/inside_test.i"
	@echo "... unit_test/inside_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

